// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.SqlServer.Types;
using ecms.Infrastructure.Database;

#nullable disable

namespace ecms.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241106210127_RemovedUserIdFromProductEntityAndAddUserIdAndDateToMaterialHistoryEntity")]
    partial class RemovedUserIdFromProductEntityAndAddUserIdAndDateToMaterialHistoryEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ecms")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ecms.Domain.Entities.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.AllergenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Allergens", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("FileGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<SqlHierarchyId>("HierarchyId")
                        .HasColumnType("hierarchyid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Categories", "ecms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HierarchyId = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/"),
                            Name = "Main"
                        });
                });

            modelBuilder.Entity("ecms.Domain.Entities.InvoiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("FileGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Invoices", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.MaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("FileGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MaxStockLevel")
                        .HasColumnType("float");

                    b.Property<double>("MinStockLevel")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ReorderLevel")
                        .HasColumnType("float");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.MaterialHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("FileGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<double>("MaxStockLevel")
                        .HasColumnType("float");

                    b.Property<double>("MinStockLevel")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ReorderLevel")
                        .HasColumnType("float");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialHistories", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("ErrorAttempts")
                        .HasColumnType("int");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MessageStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SentDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Messages", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Orders", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.OrderProductVariantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderProductVariants", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlcoholContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("FileGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GtuCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlcoholContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("FileGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GtuCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductHistories", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductMaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductEntityId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductEntityId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductMaterials", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductMaterialHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatorUsedId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductMaterialId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductMaterialId");

                    b.ToTable("ProductMaterialHistories", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductVariantAllergenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AllergenId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductVariantAllergens", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductVariantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductVariantHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductVariantHistories", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.StockEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Stocks", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.StockLevelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId")
                        .IsUnique();

                    b.HasIndex("StockId");

                    b.ToTable("StockLevels", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.StockTransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("ExpiryDate")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierOrderMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("[OrderId] IS NOT NULL");

                    b.HasIndex("StockLevelId");

                    b.HasIndex("SupplierOrderMaterialId")
                        .IsUnique()
                        .HasFilter("[SupplierOrderMaterialId] IS NOT NULL");

                    b.ToTable("StockTransactions", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCommon")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierContacts", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Suppliers", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateDateTimeUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierHistories", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DeliveryDate")
                        .IsRequired()
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierOrders", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierOrderMaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SupplierOrderId");

                    b.ToTable("SupplierOrderMaterials", "ecms");
                });

            modelBuilder.Entity("ecms.Domain.Entities.InvoiceEntity", b =>
                {
                    b.OwnsOne("ecms.Domain.ValueObjects.Price", "TotalPrice", b1 =>
                        {
                            b1.Property<int>("InvoiceEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Amount")
                                .HasColumnType("float")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("InvoiceEntityId");

                            b1.ToTable("Invoices", "ecms");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceEntityId");
                        });

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("ecms.Domain.Entities.MaterialHistoryEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.MaterialEntity", "Material")
                        .WithMany("MaterialHistories")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ecms.Domain.Entities.OrderEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.AddressEntity", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId");

                    b.OwnsOne("ecms.Domain.ValueObjects.Price", "TotalPrice", b1 =>
                        {
                            b1.Property<int>("OrderEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Amount")
                                .HasColumnType("float")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("OrderEntityId");

                            b1.ToTable("Orders", "ecms");

                            b1.WithOwner()
                                .HasForeignKey("OrderEntityId");
                        });

                    b.Navigation("Address");

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("ecms.Domain.Entities.OrderProductVariantEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.OrderEntity", "Order")
                        .WithMany("OrderProductVariants")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecms.Domain.Entities.ProductVariantEntity", "ProductVariant")
                        .WithMany("OrderProductVariants")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductHistoryEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.ProductEntity", "Product")
                        .WithMany("ProductHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductMaterialEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.MaterialEntity", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecms.Domain.Entities.ProductEntity", null)
                        .WithMany("ProductMaterials")
                        .HasForeignKey("ProductEntityId");

                    b.HasOne("ecms.Domain.Entities.ProductVariantEntity", "ProductVariant")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductMaterialHistoryEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.ProductMaterialEntity", "ProductMaterial")
                        .WithMany("ProductMaterialHistories")
                        .HasForeignKey("ProductMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductMaterial");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductVariantAllergenEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.AllergenEntity", "Allergen")
                        .WithMany("ProductVariantAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecms.Domain.Entities.ProductVariantEntity", "ProductVariant")
                        .WithMany("ProductVariantAllergens")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductVariantEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.ProductEntity", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ecms.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<int>("ProductVariantEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Amount")
                                .HasColumnType("float")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("ProductVariantEntityId");

                            b1.ToTable("ProductVariants", "ecms");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantEntityId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductVariantHistoryEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.ProductVariantEntity", "ProductVariant")
                        .WithMany("ProductVariantHistories")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ecms.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<int>("ProductVariantHistoryEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Amount")
                                .HasColumnType("float")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("ProductVariantHistoryEntityId");

                            b1.ToTable("ProductVariantHistories", "ecms");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantHistoryEntityId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ecms.Domain.Entities.StockEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.AddressEntity", "Address")
                        .WithMany("Stocks")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ecms.Domain.Entities.StockLevelEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.MaterialEntity", "Material")
                        .WithOne("StockLevel")
                        .HasForeignKey("ecms.Domain.Entities.StockLevelEntity", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecms.Domain.Entities.StockEntity", "Stock")
                        .WithMany("StockLevels")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ecms.Domain.Entities.StockTransactionEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.OrderEntity", "Order")
                        .WithOne("StockTransaction")
                        .HasForeignKey("ecms.Domain.Entities.StockTransactionEntity", "OrderId");

                    b.HasOne("ecms.Domain.Entities.StockLevelEntity", "StockLevel")
                        .WithMany("StockTransactions")
                        .HasForeignKey("StockLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecms.Domain.Entities.SupplierOrderMaterialEntity", "SupplierOrderMaterial")
                        .WithOne("StockTransaction")
                        .HasForeignKey("ecms.Domain.Entities.StockTransactionEntity", "SupplierOrderMaterialId");

                    b.Navigation("Order");

                    b.Navigation("StockLevel");

                    b.Navigation("SupplierOrderMaterial");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierContactEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.SupplierEntity", "Supplier")
                        .WithMany("SupplierContacts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.AddressEntity", "Address")
                        .WithMany("Suppliers")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierHistoryEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.SupplierEntity", "Supplier")
                        .WithMany("SupplierHistories")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierOrderEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.InvoiceEntity", "Invoice")
                        .WithOne("SupplierOrder")
                        .HasForeignKey("ecms.Domain.Entities.SupplierOrderEntity", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecms.Domain.Entities.SupplierEntity", "Supplier")
                        .WithMany("SupplierOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierOrderMaterialEntity", b =>
                {
                    b.HasOne("ecms.Domain.Entities.MaterialEntity", "Material")
                        .WithMany("SuppliersOrderMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecms.Domain.Entities.SupplierOrderEntity", "SupplierOrder")
                        .WithMany("SupplierOrderMaterials")
                        .HasForeignKey("SupplierOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ecms.Domain.ValueObjects.Price", "PricePerUnit", b1 =>
                        {
                            b1.Property<int>("SupplierOrderMaterialEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Amount")
                                .HasColumnType("float")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("SupplierOrderMaterialEntityId");

                            b1.ToTable("SupplierOrderMaterials", "ecms");

                            b1.WithOwner()
                                .HasForeignKey("SupplierOrderMaterialEntityId");
                        });

                    b.Navigation("Material");

                    b.Navigation("PricePerUnit")
                        .IsRequired();

                    b.Navigation("SupplierOrder");
                });

            modelBuilder.Entity("ecms.Domain.Entities.AddressEntity", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Stocks");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("ecms.Domain.Entities.AllergenEntity", b =>
                {
                    b.Navigation("ProductVariantAllergens");
                });

            modelBuilder.Entity("ecms.Domain.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ecms.Domain.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("SupplierOrder")
                        .IsRequired();
                });

            modelBuilder.Entity("ecms.Domain.Entities.MaterialEntity", b =>
                {
                    b.Navigation("MaterialHistories");

                    b.Navigation("ProductMaterials");

                    b.Navigation("StockLevel")
                        .IsRequired();

                    b.Navigation("SuppliersOrderMaterials");
                });

            modelBuilder.Entity("ecms.Domain.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderProductVariants");

                    b.Navigation("StockTransaction")
                        .IsRequired();
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductEntity", b =>
                {
                    b.Navigation("ProductHistories");

                    b.Navigation("ProductMaterials");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductMaterialEntity", b =>
                {
                    b.Navigation("ProductMaterialHistories");
                });

            modelBuilder.Entity("ecms.Domain.Entities.ProductVariantEntity", b =>
                {
                    b.Navigation("OrderProductVariants");

                    b.Navigation("ProductMaterials");

                    b.Navigation("ProductVariantAllergens");

                    b.Navigation("ProductVariantHistories");
                });

            modelBuilder.Entity("ecms.Domain.Entities.StockEntity", b =>
                {
                    b.Navigation("StockLevels");
                });

            modelBuilder.Entity("ecms.Domain.Entities.StockLevelEntity", b =>
                {
                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierEntity", b =>
                {
                    b.Navigation("SupplierContacts");

                    b.Navigation("SupplierHistories");

                    b.Navigation("SupplierOrders");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierOrderEntity", b =>
                {
                    b.Navigation("SupplierOrderMaterials");
                });

            modelBuilder.Entity("ecms.Domain.Entities.SupplierOrderMaterialEntity", b =>
                {
                    b.Navigation("StockTransaction")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
